general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    inhibit_sleep = 3 # wait until screen is locked
}

# Lock after 5 minutes idle
listener {
    timeout = 300
    on-timeout = hyprlock
}
