# See https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/

preload = ~/.config/hypr/wallpapers/berserk.png

wallpaper = HDMI-A-3,~/.config/hypr/wallpapers/berserk.png
wallpaper = DP-2,~/.config/hypr/wallpapers/berserk.png
wallpaper = HDMI-A-2,~/.config/hypr/wallpapers/berserk.png

splash = false
ipc = on
